version: '3.1'
services:
  postgres:
    image: postgres:15
    container_name: TaskPro
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: