version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taskpro_db
    restart: always
    environment:
      POSTGRES_DB: taskpro
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: